gui:
  showFileTree: true
  showCommandLog: false
git:
  paging:
    pager: delta --dark --paging=never
customCommands:
  - key: '<c-o>'
    context: 'commits'
    command: 'gh browse {{.SelectedLocalCommit.Hash}}'
    description: 'Open commit in GitHub'
