[mgr]
ratio = [1, 2, 5]

[plugin]
prepend_previewers = [
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.ipynb", run = "nbpreview" }, # https://github.com/AnirudhG07/nbpreview.yazi
  { mime = "application/bittorrent", run = "torrent-preview" }, # https://github.com/kirasok/torrent-preview.yazi
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -- "$1"' },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
]

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
