#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$REPO_DIR/local"
OUTPUT_FILE="$OUTPUT_DIR/zsh-inventory.txt"

redact_path() {
  local value="$1"
  value="${value/#$REPO_DIR/.}"
  value="${value/#$HOME/~}"
  printf '%s\n' "$value" \
    | sed -E 's#(^|/)([Tt][Oo][Kk][Ee][Nn]|[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll]|[Pp][Rr][Ii][Vv][Aa][Tt][Ee]-[Kk][Ee][Yy]|[Aa][Pp][Ii]-[Kk][Ee][Yy])[^/]*#\1[redacted]#g; s#(^|/)([A-Za-z0-9_-]{32,})#\1[redacted]#g'
}

describe_path() {
  local label="$1"
  local path_value="$2"

  if [ -L "$path_value" ]; then
    printf '%s: symlink %s -> %s\n' "$label" "$(redact_path "$path_value")" "$(redact_path "$(readlink "$path_value")")"
  elif [ -f "$path_value" ]; then
    printf '%s: file %s\n' "$label" "$(redact_path "$path_value")"
  elif [ -d "$path_value" ]; then
    printf '%s: directory %s\n' "$label" "$(redact_path "$path_value")"
  else
    printf '%s: missing %s\n' "$label" "$(redact_path "$path_value")"
  fi
}

list_directory() {
  local label="$1"
  local directory="$2"

  printf '\n[%s]\n' "$label"
  if [ ! -d "$directory" ]; then
    printf 'missing %s\n' "$(redact_path "$directory")"
    return
  fi

  find "$directory" -mindepth 1 -maxdepth 2 \( -type f -o -type d -o -type l \) -print 2>/dev/null \
    | while IFS= read -r path_value; do redact_path "$path_value"; done \
    | LC_ALL=C sort
}

mkdir -p "$OUTPUT_DIR"

{
  printf '# Redacted zsh inventory\n'
  printf '# Generated by just inventory-redacted. Paths only; file contents and environment values are intentionally omitted.\n\n'

  describe_path 'repo .zshrc' "$REPO_DIR/.zshrc"
  describe_path 'repo .p10k.zsh' "$REPO_DIR/.p10k.zsh"
  describe_path 'chezmoi zsh template' "$REPO_DIR/home/dot_zshrc.tmpl"
  describe_path 'home .zshrc' "$HOME/.zshrc"
  describe_path 'home .p10k.zsh' "$HOME/.p10k.zsh"
  describe_path 'local zsh override' "$HOME/.zshrc.local"
  describe_path 'local zprofile override' "$HOME/.zprofile.local"
  describe_path 'local zshenv override' "$HOME/.zshenv.local"

  list_directory 'zsh functions' "$HOME/.zsh/functions"
  list_directory 'zsh completions' "$HOME/.zsh/completions"
  list_directory 'xdg zsh site-functions' "${XDG_DATA_HOME:-$HOME/.local/share}/zsh/site-functions"
  list_directory 'oh-my-zsh custom plugins' "$HOME/.oh-my-zsh/custom/plugins"
  list_directory 'oh-my-zsh custom themes' "$HOME/.oh-my-zsh/custom/themes"
} >"$OUTPUT_FILE"

printf '%s\n' 'Wrote redacted zsh inventory to local/zsh-inventory.txt'
